spring:
  application:
    name: sunduq
  
  # Security OAuth2 configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: openid,profile,email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://www.googleapis.com/oauth2/v3/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  # Session configuration
  session:
    store-type: memory
    timeout: 1800s # 30 minutes
    cookie:
      name: SUNDUQ_SESSION
      max-age: 1800s
      secure: false # Set to true in production with HTTPS
      http-only: true
      same-site: lax

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      timeout: 30m
      cookie:
        name: SUNDUQ_SESSION
        max-age: 1800
        secure: false # Set to true in production
        http-only: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKey}
  expiration: 86400000 # 24 hours in milliseconds

# Logging configuration
logging:
  level:
    com.tyb.mytest: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
