name: Build JAR and Docker Image

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'
          distribution: 'temurin'

      - name: Build JAR with Maven
        run: mvn clean package -DskipTests

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: sunuq-jar
          path: ./downloaded



      - name: Build Docker image
        run: docker build -t tayyabk/sunduq:latest .

      # Optional: Push Docker image to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push tayyabk/sunduq:latest
